_target_: diffusion_policy.workspace.train_dit_hybrid_workspace.TrainDiTHybridWorkspace
checkpoint:
  save_last_ckpt: true
  save_last_snapshot: false
  topk:
    format_str: epoch={epoch:04d}-val_loss={val_loss:.3f}.ckpt
    k: 8
    mode: min
    monitor_key: val_loss
dataloader:
  batch_size: 16
  num_workers: 0
  persistent_workers: false
  pin_memory: false
  shuffle: true
dataset_obs_steps: 2
ema:
  _target_: diffusion_policy.model.diffusion.ema_model.EMAModel
  inv_gamma: 1.0
  max_value: 0.9999
  min_value: 0.0
  power: 0.75
  update_after_step: 0
exp_name: default
horizon: 16
keypoint_visible_rate: 1.0
logging:
  group: null
  id: null
  mode: online
  name: train_dit_hybrid_tr01_pickup_image_{date:%Y.%m.%d}/{time:%H.%M.%S}
  project: diffusion_policy_debug
  resume: true
  tags:
  - train_dit_hybrid
  - tr01_pickup_image
  - default
multi_run:
  run_dir: data/outputs/tr01/train_dit_hybrid_tr01_pickup_image_{date:%Y.%m.%d}/{time:%H.%M.%S}
  wandb_name_base: train_dit_hybrid_tr01_pickup_image_{date:%Y.%m.%d}/{time:%H.%M.%S}
n_action_steps: 8
n_latency_steps: 0
n_obs_steps: 4
name: train_dit_hybrid
#obs_as_global_cond: true
obs_as_cond: True
optimizer:
  transformer_weight_decay: 1.0e-3
  obs_encoder_weight_decay: 1.0e-6
  learning_rate: 1.0e-4
  betas: [ 0.9, 0.95 ]
past_action_visible: false
policy:
  _target_: diffusion_policy.policy.dit_hybrid_image_resnet_policy.DiTHybridImageResNetPolicy
  crop_shape: [600, 450]
  eval_fixed_crop: true
  freeze_resnet: true
  horizon: 16
  n_action_steps: 8
  n_obs_steps: 4
  noise_scheduler:
    _target_: diffusers.schedulers.scheduling_ddim.DDIMScheduler
    beta_end: 0.02
    beta_schedule: squaredcos_cap_v2
    beta_start: 0.0001
    clip_sample: true
    num_train_timesteps: 100
    prediction_type: epsilon
#    variance_type: fixed_small
  num_inference_steps: 8  # 100 for ddpm, 8 for ddim
#  obs_as_global_cond: true
  obs_as_cond: True
  obs_encoder_group_norm: true

  n_layer: 8
  n_cond_layers: 0  # >0: use transformer encoder for cond, otherwise use MLP
  n_head: 4
  n_emb: 256
  p_drop_emb: 0.0
  p_drop_attn: 0.3
  causal_attn: True
  time_as_cond: True # if false, use BERT like encoder only arch, time as input

  shape_meta:
    action:
      shape:
      - 15
    obs:
      ur5_joint_pos:
        shape:
          - 6
        type: low_dim
      hand_joint_pos:
        shape:
          - 8
        type: low_dim
      ur5_ee_pose:
        shape:
          - 7
        type: low_dim
      camera_rgb_image:
        shape:
        - 3
        - 640
        - 480
        type: rgb
shape_meta:
  action:
    shape:
    - 15
  obs:
    ur5_joint_pos:
      shape:
        - 6
      type: low_dim
    hand_joint_pos:
      shape:
        - 8
      type: low_dim
    ur5_ee_pose:
      shape:
        - 7
      type: low_dim
    camera_rgb_image:
      shape:
      - 3
      - 640
      - 480
      type: rgb
task:
  dataset:
    _target_: diffusion_policy.dataset.tr01_pickup_image_dataset.PickupImageDataset
    horizon: 16
    max_train_episodes: None
    pad_after: 7
    pad_before: 3
    seed: 42
    val_ratio: 0.02
    zarr_path: ../diffusion_policy/data/pickup_yellow.zarr
    use_rel_actions: false
    data_freq: 20
    learning_freq: 20
  env_runner:
    _target_: diffusion_policy.env_runner.base_image_runner.BaseImageRunner
  image_shape:
  - 3
  - 640
  - 480
  name: pickup_image
  shape_meta:
    action:
      shape:
      - 15
    obs:
      ur5_joint_pos:
        shape:
        - 6
        type: low_dim
      hand_joint_pos:
        shape:
          - 8
        type: low_dim
      ur5_ee_pose:
        shape:
          - 7
        type: low_dim
      camera_rgb_image:
        shape:
        - 3
        - 640
        - 480
        type: rgb
task_name: pickup_image
training:
  checkpoint_every: 5
  debug: false
  device: cuda:0
  gradient_accumulate_every: 1
  lr_scheduler: cosine
  lr_warmup_steps: 500
  max_train_steps: null
  max_val_steps: null
  num_epochs: 3050
  resume: true
  rollout_every: 50
  sample_every: 5
  seed: 42
  tqdm_interval_sec: 1.0
  use_ema: true
  val_every: 1
val_dataloader:
  batch_size: 16
  num_workers: 0
  persistent_workers: false
  pin_memory: false
  shuffle: false
